import { DateTime } from "luxon";

import BillingPeriod from "../models/BillingPeriod.js";
import HttpError from "./HttpError.js";

const getApplicationTimezone = () => {
  return process.env.APP_TIMEZONE || "Asia/Colombo";
};

export const getCurrentMonthCycle = (
  currentDate = new Date()
) => {
  const timezone = getApplicationTimezone();

  const currentDateTime = DateTime
    .fromJSDate(currentDate)
    .setZone(timezone);

  if (!currentDateTime.isValid) {
    throw new Error(
      `Invalid application timezone: ${timezone}`
    );
  }

  const monthStart =
    currentDateTime.startOf("month");

  const monthEnd =
    currentDateTime.endOf("month");

  return {
    year: monthStart.year,
    month: monthStart.month,

    label: monthStart.toFormat("LLLL yyyy"),

    accessStartsAt:
      monthStart.toUTC().toJSDate(),

    accessEndsAt:
      monthEnd.toUTC().toJSDate(),

    paymentDeadline:
      monthEnd.toUTC().toJSDate(),

    timezone,
  };
};

export const getOrCreateCurrentBillingPeriod =
  async (course) => {
    if (!course?._id) {
      throw new HttpError(
        400,
        "A valid course is required."
      );
    }

    if (course.paymentPlan !== "monthly") {
      throw new HttpError(
        400,
        "This course does not use monthly billing."
      );
    }

    if (!course.createdBy) {
      throw new HttpError(
        500,
        "The course does not have a valid creator."
      );
    }

    const cycle = getCurrentMonthCycle();

    const filter = {
      course: course._id,
      year: cycle.year,
      month: cycle.month,
    };

    try {
      const billingPeriod =
        await BillingPeriod.findOneAndUpdate(
          filter,
          {
            $setOnInsert: {
              course: course._id,

              year: cycle.year,
              month: cycle.month,
              label: cycle.label,

              /*
               * The monthly amount is copied from
               * the course when the period is created.
               *
               * Changing the course price later will
               * not change this month's existing amount.
               */
              amount: course.price,
              currency: course.currency || "LKR",

              accessStartsAt:
                cycle.accessStartsAt,

              accessEndsAt:
                cycle.accessEndsAt,

              paymentDeadline:
                cycle.paymentDeadline,

              isPublished: true,
              isPaymentOpen: true,
              isArchived: false,
              isAutoGenerated: true,

              createdBy: course.createdBy,
              updatedBy:
                course.updatedBy ||
                course.createdBy,
            },
          },
          {
            new: true,
            upsert: true,
            runValidators: true,
            setDefaultsOnInsert: true,
          }
        );

      return billingPeriod;
    } catch (error) {
      /*
       * Two requests could arrive at nearly
       * the same time. The unique database
       * index prevents duplicate periods.
       */
      if (error.code === 11000) {
        const existingPeriod =
          await BillingPeriod.findOne(filter);

        if (existingPeriod) {
          return existingPeriod;
        }
      }

      throw error;
    }
  };