import schedule from "node-schedule";

import Course from "../models/Course.js";
import {
  getBillingReferenceDate,
  getOrCreateCurrentBillingPeriod,
  synchronizeCourseBillingPeriodDates,
} from "./billingPeriod.js";

import {
  sendDuePaymentReminders,
} from "../services/paymentReminderService.js";
import { processPendingNotificationEmails } from "../services/notificationService.js";
import {
  retryPendingZoomRegistrations,
  retryPendingZoomRevocations,
} from "../services/zoomRegistrationService.js";
import { runWithJobLease } from "./jobLease.js";
import {
  enforceMonthlyEnrollmentAccess,
} from "../services/monthlyAccessEnforcementService.js";

const getApplicationTimezone = () => {
  return process.env.APP_TIMEZONE || "Asia/Colombo";
};

/**
 * Shared billing-generation function.
 * Used by:
 * - Scheduled monthly job
 * - Manual admin trigger
 * - Server-start catch-up
 */
const runMonthlyBillingGeneration = async ({
  source = "scheduled",
} = {}) => {
  const startedAt = new Date();

  console.log(
    `[BILLING_JOB:${source}] Billing generation started at ${startedAt.toISOString()}`
  );

  const monthlyCourses = await Course.find({
    paymentPlan: "monthly",
    isPublished: true,
    isArchived: false,
  }).select(
    "_id title price currency createdBy updatedBy paymentPlan"
  );

  let successCount = 0;
  let failureCount = 0;

  const failedCourses = [];
  const generatedPeriods = [];

  for (const course of monthlyCourses) {
    try {
      const billingPeriod =
        await getOrCreateCurrentBillingPeriod(course);
      await synchronizeCourseBillingPeriodDates(course._id);

      successCount += 1;

      generatedPeriods.push({
        courseId: course._id,
        courseTitle: course.title,
        billingPeriodId: billingPeriod._id,
        periodLabel: billingPeriod.label,
        isPublished: billingPeriod.isPublished,
        isAutoGenerated: billingPeriod.isAutoGenerated,
      });

      console.log(
        `[BILLING_JOB:${source}] ${course.title}: ${billingPeriod.label}`
      );
    } catch (error) {
      failureCount += 1;

      failedCourses.push({
        courseId: course._id,
        courseTitle: course.title,
        error: error.message,
      });

      console.error(
        `[BILLING_JOB:${source}] Failed for ${course.title}:`,
        error.message
      );
    }
  }

  const completedAt = new Date();

  const result = {
    success: failureCount === 0,
    successCount,
    failureCount,
    failedCourses,
    generatedPeriods,
    durationMs:
      completedAt.getTime() - startedAt.getTime(),
    completedAt: completedAt.toISOString(),
  };

  console.log(
    `[BILLING_JOB:${source}] Completed: ${successCount} succeeded, ${failureCount} failed`
  );

  return result;
};

/**
 * Production:
 * Runs at 00:01 on the first day of every month.
 *
 * Development test mode:
 * Runs at second 0 of every minute.
 */
export const scheduleMonthlyBillingGeneration = () => {
  const timezone = getApplicationTimezone();

  const rule = new schedule.RecurrenceRule();

  rule.tz = timezone;

  /*
   * ORIGINAL PRODUCTION SCHEDULE
   *
   * These were your original lines.
   * They are kept here as comments as requested.
   */

  // rule.date = 1;
  // rule.hour = 0;
  // rule.minute = 1;
  // rule.second = 0;

  /*
   * Test mode is active only when:
   *
   * NODE_ENV=development
   * BILLING_CRON_TEST_MODE=true
   */
  const testMode =
    process.env.NODE_ENV === "development" &&
    process.env.BILLING_CRON_TEST_MODE === "true";

  if (testMode) {
    /*
     * Runs every minute at second 0.
     *
     * Examples:
     * 10:20:00
     * 10:21:00
     * 10:22:00
     */
    rule.second = 0;

    console.log(
      "[BILLING_JOB] TEST MODE enabled: billing job runs every minute."
    );
  } else {
    /*
     * Normal production schedule.
     *
     * Runs at:
     * 00:01 on the first day of every month
     * using the configured timezone.
     */
    rule.date = 1;
    rule.hour = 0;
    rule.minute = 1;
    rule.second = 0;

    console.log(
      `[BILLING_JOB] PRODUCTION MODE: billing job runs on the first day of each month at 00:01 in ${timezone}.`
    );
  }

  const job = schedule.scheduleJob(
    rule,
    async (fireDate) => {
      console.log(
        `[BILLING_JOB] Scheduled execution time: ${fireDate.toISOString()}`
      );

      try {
        await runWithJobLease(
          "monthly-billing-generation",
          () => runMonthlyBillingGeneration({ source: "scheduled" }),
          { leaseMilliseconds: 30 * 60 * 1000 }
        );
      } catch (error) {
        console.error(
          "[BILLING_JOB] Critical scheduled-job error:",
          error
        );
      }
    }
  );

  if (!job) {
    throw new Error(
      "Monthly billing job could not be scheduled."
    );
  }

  console.log(
    `[BILLING_JOB] Monthly billing job scheduled in ${timezone}.`
  );

  console.log(
    `[BILLING_JOB] Next execution: ${
      job.nextInvocation()?.toISOString() ||
      "unknown"
    }`
  );

  return job;
};

export const triggerMonthlyBillingGenerationNow =
  async () => {
    return runWithJobLease(
      "monthly-billing-generation",
      () => runMonthlyBillingGeneration({ source: "manual" }),
      { leaseMilliseconds: 30 * 60 * 1000 }
    );
  };

export const runBillingGenerationOnStartup =
  async () => {
    return runWithJobLease(
      "monthly-billing-generation",
      () => runMonthlyBillingGeneration({ source: "startup" }),
      { leaseMilliseconds: 30 * 60 * 1000 }
    );
  };

export const schedulePaymentReminders = () => {
  const timezone = getApplicationTimezone();
  const configuredHour = Number.parseInt(
    process.env.PAYMENT_REMINDER_HOUR || "9",
    10,
  );
  const hour = Number.isInteger(configuredHour) &&
    configuredHour >= 0 && configuredHour <= 23
    ? configuredHour
    : 9;

  const rule = new schedule.RecurrenceRule();
  rule.tz = timezone;
  rule.hour = hour;
  rule.minute = 0;
  rule.second = 0;

  const job = schedule.scheduleJob(rule, async () => {
    try {
      await runWithJobLease(
        "payment-reminders",
        () => sendDuePaymentReminders({ source: "scheduled" }),
        { leaseMilliseconds: 30 * 60 * 1000 }
      );
    } catch (error) {
      console.error(
        "[PAYMENT_REMINDER] Scheduled job failed:",
        error.message,
      );
    }
  });

  if (!job) {
    throw new Error("Payment reminder job could not be scheduled.");
  }

  console.log(
    `[PAYMENT_REMINDER] Scheduled daily at ${String(hour).padStart(2, "0")}:00 in ${timezone}.`,
  );

  return job;
};

export const runPaymentRemindersOnStartup = async () => {
  return runWithJobLease(
    "payment-reminders",
    () => sendDuePaymentReminders({ source: "startup" }),
    { leaseMilliseconds: 30 * 60 * 1000 }
  );
};

const runMonthlyAccessEnforcement = async ({ source = "scheduled" } = {}) => {
  return runWithJobLease(
    "monthly-access-enforcement",
    () =>
      enforceMonthlyEnrollmentAccess({
        now: getBillingReferenceDate(),
        source,
      }),
    { leaseMilliseconds: 30 * 60 * 1000 }
  );
};

export const scheduleMonthlyAccessEnforcement = () => {
  const timezone = getApplicationTimezone();
  const rule = new schedule.RecurrenceRule();
  rule.tz = timezone;

  const testMode =
    process.env.NODE_ENV === "development" &&
    process.env.BILLING_CRON_TEST_MODE === "true";

  if (testMode) {
    rule.second = 15;
    console.log(
      "[MONTHLY_ACCESS] TEST MODE enabled: access enforcement runs every minute."
    );
  } else {
    rule.hour = 0;
    rule.minute = 0;
    rule.second = 5;
  }

  const job = schedule.scheduleJob(rule, () => {
    void runMonthlyAccessEnforcement({ source: "scheduled" }).catch((error) => {
      console.error("[MONTHLY_ACCESS] Scheduled job failed:", error.message);
    });
  });

  if (!job) {
    throw new Error("Monthly access enforcement job could not be scheduled.");
  }

  console.log(
    `[MONTHLY_ACCESS] Scheduled daily at 00:00:05 in ${timezone}.`
  );
  return job;
};

export const runMonthlyAccessEnforcementOnStartup = () => {
  return runMonthlyAccessEnforcement({ source: "startup" });
};

export const triggerMonthlyAccessEnforcementNow = () => {
  return runMonthlyAccessEnforcement({ source: "manual" });
};

const runBackgroundMaintenance = async () => {
  return runWithJobLease(
    "notification-and-zoom-retries",
    async () => {
      const [email, zoom, zoomRevocations] = await Promise.all([
        processPendingNotificationEmails({ limit: 50 }),
        retryPendingZoomRegistrations({ limit: 20 }),
        retryPendingZoomRevocations({ limit: 20 }),
      ]);

      console.log("[MAINTENANCE] Retry processing completed:", {
        email,
        zoom,
        zoomRevocations,
      });
      return { email, zoom, zoomRevocations };
    },
    { leaseMilliseconds: 10 * 60 * 1000 }
  );
};

export const scheduleBackgroundMaintenance = () => {
  const rule = new schedule.RecurrenceRule();
  rule.tz = getApplicationTimezone();
  rule.minute = new schedule.Range(0, 59, 5);
  rule.second = 30;

  const job = schedule.scheduleJob(rule, () => {
    void runBackgroundMaintenance().catch((error) => {
      console.error("[MAINTENANCE] Scheduled retry processing failed:", error.message);
    });
  });

  if (!job) {
    throw new Error("Background maintenance job could not be scheduled.");
  }

  return job;
};

export const runBackgroundMaintenanceOnStartup = runBackgroundMaintenance;

export const shutdownScheduledJobs = async () => {
  await schedule.gracefulShutdown();
};
