import schedule from "node-schedule";

import Course from "../models/Course.js";
import {
  getOrCreateCurrentBillingPeriod,
} from "./billingPeriod.js";

const getApplicationTimezone = () => {
  return process.env.APP_TIMEZONE || "Asia/Colombo";
};

/**
 * Shared billing-generation function.
 * Used by:
 * - Scheduled monthly job
 * - Manual admin trigger
 * - Server-start catch-up
 */
const runMonthlyBillingGeneration = async ({
  source = "scheduled",
} = {}) => {
  const startedAt = new Date();

  console.log(
    `[BILLING_JOB:${source}] Billing generation started at ${startedAt.toISOString()}`
  );

  const monthlyCourses = await Course.find({
    paymentPlan: "monthly",
    isPublished: true,
    isArchived: false,
  }).select(
    "_id title price currency createdBy updatedBy paymentPlan"
  );

  let successCount = 0;
  let failureCount = 0;

  const failedCourses = [];
  const generatedPeriods = [];

  for (const course of monthlyCourses) {
    try {
      const billingPeriod =
        await getOrCreateCurrentBillingPeriod(course);

      successCount += 1;

      generatedPeriods.push({
        courseId: course._id,
        courseTitle: course.title,
        billingPeriodId: billingPeriod._id,
        periodLabel: billingPeriod.label,
        isPublished: billingPeriod.isPublished,
        isAutoGenerated: billingPeriod.isAutoGenerated,
      });

      console.log(
        `[BILLING_JOB:${source}] ${course.title}: ${billingPeriod.label}`
      );
    } catch (error) {
      failureCount += 1;

      failedCourses.push({
        courseId: course._id,
        courseTitle: course.title,
        error: error.message,
      });

      console.error(
        `[BILLING_JOB:${source}] Failed for ${course.title}:`,
        error.message
      );
    }
  }

  const completedAt = new Date();

  const result = {
    success: failureCount === 0,
    successCount,
    failureCount,
    failedCourses,
    generatedPeriods,
    durationMs:
      completedAt.getTime() - startedAt.getTime(),
    completedAt: completedAt.toISOString(),
  };

  console.log(
    `[BILLING_JOB:${source}] Completed: ${successCount} succeeded, ${failureCount} failed`
  );

  return result;
};

/**
 * Production:
 * Runs at 00:01 on the first day of every month.
 *
 * Development test mode:
 * Runs at second 0 of every minute.
 */
export const scheduleMonthlyBillingGeneration = () => {
  const timezone = getApplicationTimezone();

  const rule = new schedule.RecurrenceRule();

  rule.tz = timezone;

  /*
   * ORIGINAL PRODUCTION SCHEDULE
   *
   * These were your original lines.
   * They are kept here as comments as requested.
   */

  // rule.date = 1;
  // rule.hour = 0;
  // rule.minute = 1;
  // rule.second = 0;

  /*
   * Test mode is active only when:
   *
   * NODE_ENV=development
   * BILLING_CRON_TEST_MODE=true
   */
  const testMode =
    process.env.NODE_ENV === "development" &&
    process.env.BILLING_CRON_TEST_MODE === "true";

  if (testMode) {
    /*
     * Runs every minute at second 0.
     *
     * Examples:
     * 10:20:00
     * 10:21:00
     * 10:22:00
     */
    rule.second = 0;

    console.log(
      "[BILLING_JOB] TEST MODE enabled: billing job runs every minute."
    );
  } else {
    /*
     * Normal production schedule.
     *
     * Runs at:
     * 00:01 on the first day of every month
     * using the configured timezone.
     */
    rule.date = 1;
    rule.hour = 0;
    rule.minute = 1;
    rule.second = 0;

    console.log(
      `[BILLING_JOB] PRODUCTION MODE: billing job runs on the first day of each month at 00:01 in ${timezone}.`
    );
  }

  const job = schedule.scheduleJob(
    rule,
    async (fireDate) => {
      console.log(
        `[BILLING_JOB] Scheduled execution time: ${fireDate.toISOString()}`
      );

      try {
        await runMonthlyBillingGeneration({
          source: "scheduled",
        });
      } catch (error) {
        console.error(
          "[BILLING_JOB] Critical scheduled-job error:",
          error
        );
      }
    }
  );

  if (!job) {
    throw new Error(
      "Monthly billing job could not be scheduled."
    );
  }

  console.log(
    `[BILLING_JOB] Monthly billing job scheduled in ${timezone}.`
  );

  console.log(
    `[BILLING_JOB] Next execution: ${
      job.nextInvocation()?.toISOString() ||
      "unknown"
    }`
  );

  return job;
};

export const triggerMonthlyBillingGenerationNow =
  async () => {
    return runMonthlyBillingGeneration({
      source: "manual",
    });
  };

export const runBillingGenerationOnStartup =
  async () => {
    return runMonthlyBillingGeneration({
      source: "startup",
    });
  };

export const shutdownScheduledJobs = async () => {
  await schedule.gracefulShutdown();
};