import mongoose from "mongoose";

const monthNames = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

const billingPeriodSchema =
  new mongoose.Schema(
    {
      course: {
        type:
          mongoose.Schema.Types.ObjectId,
        ref: "Course",
        required: true,
      },

      year: {
        type: Number,
        required: true,
        min: 2020,
        max: 2100,
      },

      month: {
        type: Number,
        required: true,
        min: 1,
        max: 12,
      },

      label: {
        type: String,
        required: true,
        trim: true,
        maxlength: 100,
      },

      amount: {
        type: Number,
        required: true,
        min: 0,
      },

      currency: {
        type: String,
        default: "LKR",
        uppercase: true,
        trim: true,
        maxlength: 10,
      },

      accessStartsAt: {
        type: Date,
        required: true,
      },

      accessEndsAt: {
        type: Date,
        required: true,
      },

      paymentDeadline: {
        type: Date,
        default: null,
      },

      isPublished: {
        type: Boolean,
        default: false,
      },

      isPaymentOpen: {
        type: Boolean,
        default: true,
      },

      isArchived: {
        type: Boolean,
        default: false,
      },
      
      isAutoGenerated: {
        type: Boolean,
        default: false,
      },

      createdBy: {
        type:
          mongoose.Schema.Types.ObjectId,
        ref: "User",
        required: true,
      },

      updatedBy: {
        type:
          mongoose.Schema.Types.ObjectId,
        ref: "User",
        default: null,
      },
      
    },
    {
      timestamps: true,

      toJSON: {
        transform: (_, object) => {
          delete object.__v;
          return object;
        },
      },
    }
  );

billingPeriodSchema.pre(
  "validate",
  function () {
    if (
      !this.label &&
      this.year &&
      this.month
    ) {
      this.label = `${
        monthNames[this.month - 1]
      } ${this.year}`;
    }

    if (
      this.accessStartsAt &&
      this.accessEndsAt &&
      this.accessEndsAt <=
        this.accessStartsAt
    ) {
      this.invalidate(
        "accessEndsAt",
        "Access end date must be later than the start date."
      );
    }
  }
);

billingPeriodSchema.index(
  {
    course: 1,
    year: 1,
    month: 1,
  },
  {
    unique: true,
  }
);

billingPeriodSchema.index({
  course: 1,
  isPublished: 1,
  isArchived: 1,
  year: -1,
  month: -1,
});

const BillingPeriod = mongoose.model(
  "BillingPeriod",
  billingPeriodSchema
);

export default BillingPeriod;